### ISSUE TITLE
The Known-Object metrics of 'base-verb'

### ISSUE THREAD

**Issue by Deicide-PiLi** [YueLiao/gen-vlkt#21]
Hi, thank you for your great work:)
Are there the metrics of 'base-verb' experiment evaluated in **Known-Object** mode?
Thanks!

**Comment by YueLiao** [comment]
Thanks for your interest in our work! The "Known Object" setting is only an evaluation mechanism, and the mAP with this setting can be obtained from the official evaluation scripts. You could follow the official evaluation steps introduced in the "README.md".

**Comment by Deicide-PiLi** [comment]
Thanks for your reply. I would like to follow your work in my paper, but I can not find the codes and corresponding checkpoint of "base-verb". Could you provide these metrics or provide the prediction results?

**Comment by YueLiao** [comment]
The original code and checkpoint have been missed, and we have re-implemented a [version](https://drive.google.com/file/d/1fZi95xNCHMzomwBy8V0aqkMybBnBcYUR/view?usp=share_link), but without sufficient training to verify its correctness, due to lacking GPUs recently. Thus, we haven't updated this setting now. You could run with the 'base-verb' setting by changing the value of 'hoi_mode.'

**Comment by Deicide-PiLi** [comment]
OK, thanks.
